require('dotenv').config();

// asset types
const ASSET_TYPE_AVATAR = 'avatar';
const ASSET_TYPE_CHUNK = 'chunk';
const ASSET_TYPE_MANIFEST = 'manifest';
const ASSET_TYPE_THUMBNAIL = 'thumnail';

// like types
const LIKE_TYPE_VIDEO = 'VIDEO_LIKE';
const LIKE_TYPE_COMMENT = 'COMMENT_LIKE';

// notification types
const NOTIFICATION_TYPE_LIKE_COMMENT = 'LIKE_COMMENT';
const NOTIFICATION_TYPE_LIKE_VIDEO = 'LIKE_VIDEO';
const NOTIFICATION_TYPE_COMMENT = 'COMMENT';
const NOTIFICATION_TYPE_FOLLOW = 'FOLLOW';

// video status
const VIDEO_STATUS_DRAFT = 'draft';
const VIDEO_STATUS_PUBLISHED = 'published';
const VIDEO_STATUS_DELETED = 'deleted';

// video access mode
const VIDEO_MODE_PUBLIC = 'public';
const VIDEO_MODE_PRIVATE = 'private';

// no avatar image file name
const NO_AVATAR_FILENAME = 'no_avatar.jpg';

module.exports = {
  ASSET_TYPE_AVATAR,
  ASSET_TYPE_CHUNK,
  ASSET_TYPE_MANIFEST,
  ASSET_TYPE_THUMBNAIL,
  NOTIFICATION_TYPE_COMMENT,
  NOTIFICATION_TYPE_LIKE_COMMENT,
  NOTIFICATION_TYPE_LIKE_VIDEO,
  NOTIFICATION_TYPE_FOLLOW,
  VIDEO_STATUS_DRAFT,
  VIDEO_STATUS_PUBLISHED,
  VIDEO_STATUS_DELETED,
  VIDEO_MODE_PRIVATE,
  VIDEO_MODE_PUBLIC,
  NO_AVATAR_FILENAME,
  LIKE_TYPE_COMMENT,
  LIKE_TYPE_VIDEO,
};
